config/routes.rb
Rails.application.routes.draw do
  resources :games
  devise_for :users
  root 'games#index'
  get "about" => "pages#about"

end

app/models/game.rb
class Game < ActiveRecord::Base
    belongs_to :user

  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :games

  validates :name, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
 before_filter :configure_permitted_parameters, if: :devise_controller?

protected

# def configure_permitted_parameters
#   devise_parameter_sanitizer.for(:sign_up) << :name
#   devise_parameter_sanitizer.for(:account_update) << :name
# end
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = current_user.games.build
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = current_user.games.build(game_params)
    if @game.save
      redirect_to @game, notice: 'Game was successfully created.' 
    else
      render new
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    if @game.update(game_params)
      redirect_to @game, notice: 'Game was successfully updated.' 
    else
      render edit
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    redirect_to games_url 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find_by(id: params[:id])
    end

    def correct_user
      @game = current_user.games.find_by(id: params[:id])
      redirect_to games_path, notice: "Not authorized to edit this game" if @game.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:description, :image, :sport, :level, :location, :price, :players, :daytime)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about 
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/games/_form.html.erb
<%= form_for @game, html: { multipart: true } do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="panel panel-default">
	<div class="panel-heading">
	</div>
	<div class="panel-body">

  <div class="form-group">
    <%= f.label :sport %>
    <%= f.text_field :sport, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :level %>
    <%= f.text_field :level, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :location %>
    <%= f.text_field :location, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :players %>
    <%= f.text_field :players, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :Date %>
    <%= f.text_field :daytime, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
	</div>
	</div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="games" class="transitions-enabled">
  <% @games.each do |game| %>
    <div class="box panel panel-default">
      <div class="panel-body">
      Sport: <%= game.sport %><br/>
      Level: <%= game.level %><br/>
      Location: <%= game.location %><br/>
      Price: $<%= game.price %><br/>
      Players: <%= game.players %><br/>
      Date: <%= game.daytime %><br/>
      Description: <%= game.description %><br/>
      <strong><%= game.user.name if game.user %></strong>
      <% if game.user == current_user %>
      <div class="actions">
             <%= link_to edit_game_path(game) do %>
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>
            <%= link_to game, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>
         </div>
        <% end %>
      <% if game.user != current_user %>
      <div class="actions">
             <%= link_to game do %>
              <span class="glyphicon glyphicon-thumbs-up"></span>
              Join
        <% end %>
      </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="center">
   <%= will_paginate @games, renderer: BootstrapPagination::Rails %>
</div>

app/views/games/new.html.erb
<%= render 'form' %>

app/views/games/show.html.erb
<%= link_to 'Back', games_path %>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
      </div>
      <div class="panel-body">
        <p>Sport: <%= @game.sport %></p>
        <p>Level: <%= @game.level %></p>
        <p>Location: <%= @game.location %></p>
        <p>Price: <%= @game.price %></p>
        <p>Players: <%= @game.players %></p>
        <p>Date: <%= @game.daytime %></p>
        <p>Description: <%= @game.description %></p>
        <p><strong><%= @game.user.name if @game.user %></strong></p>
      <% if @game.user == current_user %>
      <%= link_to edit_game_path(@game) do %>
        <span class="glyphicon glyphicon-edit"></span>
        Edit
        <% end %>
        <% end %>
      <% if @game.user != current_user %>
      <div class="actions">
             <%= link_to @game do %>
              <span class="glyphicon glyphicon-thumbs-up"></span>
              Confirm Join
            <% end %>
      </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
    </button>
    <a class="navbar-brand page-scroll" href="#page-top">Ludi</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if user_signed_in? %>
        <li>
            <%= link_to new_game_path do %>
              <span class="glyphicon glyphicon-plus"></span> New Game
            <% end %> 
        </li>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %> 
    </ul>
  </div><!-- /.navbar-collapse -->
 </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ludi</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>
	<%= render 'layouts/header' %>
<!--	<div class="container"> -->
<!--	 </div> -->
<hr>
		<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
    <% end %>
		<%= yield %>
</body>
</html>

app/views/pages/_home.html.erb
<body id="page-top">
    <header>
        <div class="header-content">
            <div class="header-content-inner">
                <h1 id="homeHeading">Where Teams and Athletes Come to Play</h1>
                <hr>
                <p>Ludi allows you to play your favorite sport by connecting you to athletes and teams around you!</p>
                <p>Please Log In or Sign Up to get started.</p>
     	<p>
       <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
       <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  		</p>

        <!--<div class="container">-->
        <!--    <div class="row">-->
        <!--        <div class="col-lg-6 col-md-6 text-center">-->
        <!--            <div class="service-box">-->
        <!--                <i class="fa fa-4x fa-gamepad text-primary sr-icons"></i>-->
        <!--                <a href="home/findagame.html">-->
        <!--                <h3>Find A Game</h3>-->
        <!--                </a>-->
        <!--                <p class="text-muted">Want to join a team or find a game happening near you?</p>-->
        <!--            </div>-->
        <!--        </div>-->
        <!--        <div class="col-lg-3 col-md-6 text-center">-->
        <!--            <div class="service-box">-->
        <!--                <i class="fa fa-4x fa-shield text-primary sr-icons"></i>-->
        <!--                <a href="home/postagame.html">-->
        <!--                <h3>Post A Game</h3>-->
        <!--                </a>-->
        <!--                <p class="text-muted">Want to start a new game or form a team?</p>-->
        <!--            </div>-->
        <!--        </div>-->
        <!--    </div>-->
        <!--</div>-->
            </div>
        </div>
    </header>

    <aside class="bg-dark">
        <div class="container text-center">
            <div class="call-to-action">
                <h2>IOS and Android Apps Coming Soon!</h2>
        <!--        <a href="#" class="btn btn-default btn-xl sr-button">Download Now!</a>-->
            </div>
        </div>
    </aside>

    <section id="contact">
        <div class="container">
         <div class="row">
             <div class="col-lg-8 col-lg-offset-2 text-center">
                 <h2 class="section-heading">Let's Get In Touch!</h2>
                 <hr class="primary">
                 <p>Want to get involved with Ludi or provide us with some feedback? That's great! Send us an email and we will get back to you as soon as possible!</p>
             </div>
            
             <div class="col-lg-12 text-center">
                 <i class="fa fa-envelope-o fa-3x sr-contact"></i>
                 <p><a href="mailto:your-email@your-domain.ca">feedback@ludi.ca</a></p>
             </div>
         </div>
     </div>
    </section>

    <aside class="bg-dark">
        <div class="container text-center">
            <div class="call-to-action">
                <h2>Recent games added to Ludi</h2>
            </div>
        </div>
    </aside>
    
    <!-- jQuery -->
    <script src="vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="vendor/scrollreveal/scrollreveal.min.js"></script>
    <script src="vendor/magnific-popup/jquery.magnific-popup.min.js"></script>
    <!-- Theme JavaScript -->
    <script src="js/creative.min.js"></script>

</body>

app/views/pages/about.html.erb
<body id="page-top">
    <header>
        <div class="header-content">
            <div class="header-content-inner">
                <h1 id="homeHeading">About Ludi</h1>
                <hr>
                <p>At Ludi we believe the power of sports and social networking are able to improve the overall health and well-being of our society by encouraging people to stay active, get outdoors, and make new friends. </p>
                <h2>Let's Ludi!</h2>
            </div>
        </div>
    </header>

    <aside class="bg-dark">
        <div class="container text-center">
            <div class="call-to-action">
                <h2>IOS and Android Apps Coming Soon!</h2>
                <a href="#" class="btn btn-default btn-xl sr-button">Download Now!</a>
            </div>
        </div>
    </aside>

    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Let's Get In Touch!</h2>
                    <hr class="primary">
                    <p>Want to get involved with Ludi? That's great! Give us a call or send us an email and we will get back to you as soon as possible!</p>
                </div>
                <div class="col-lg-4 col-lg-offset-2 text-center">
                    <i class="fa fa-phone fa-3x sr-contact"></i>
                    <p>123-456-6789</p>
                </div>
                <div class="col-lg-4 text-center">
                    <i class="fa fa-envelope-o fa-3x sr-contact"></i>
                    <p><a href="mailto:your-email@your-domain.com">feedback@ludi.com</a></p>
                </div>
            </div>
        </div>
    </section>

    <!-- jQuery -->
    <script src="vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="vendor/scrollreveal/scrollreveal.min.js"></script>
    <script src="vendor/magnific-popup/jquery.magnific-popup.min.js"></script>
    <!-- Theme JavaScript -->
    <script src="js/creative.min.js"></script>

</body>